<?php

namespace Amenophis\SympressBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostMetaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostMetaRepository extends EntityRepository
{
}
