services:
    kernel.listener.plugins_loader:
        class: Amenophis\SympressBundle\Listener\PluginsLoaderListener
        arguments: [%kernel.root_dir%]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    kernel.listener.themes_loader:
        class: Amenophis\SympressBundle\Listener\ThemesLoaderListener
        arguments: [%kernel.root_dir%]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }