<?php

namespace Amenophis\Sympress\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    public function getCountForStatus($status)
    {
        return $this->createQueryBuilder('p')
            ->select('COUNT(p)')
            ->where('p.status = :status')
            ->setParameter('status', $status)
            ->getQuery()
            ->getSingleScalarResult();
    }

    public function findByStatus($status)
    {
        return $this->findBy(array('status' => $status));
    }
}
